name: Lime neko

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.1.2
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
    - name: Build project
      run: |
        haxelib run lime build neko
